databases:
  - name: actionplan
    databaseName: actionplan
    user: bwood

services:
  - type: web
    name: actionplan
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: actionplan
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false