 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/blocks", type: :request do
  # Block. As you add validations to Block, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Block.create! valid_attributes
      get blocks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      block = Block.create! valid_attributes
      get block_url(block)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_block_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      block = Block.create! valid_attributes
      get edit_block_url(block)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Block" do
        expect {
          post blocks_url, params: { block: valid_attributes }
        }.to change(Block, :count).by(1)
      end

      it "redirects to the created block" do
        post blocks_url, params: { block: valid_attributes }
        expect(response).to redirect_to(block_url(Block.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Block" do
        expect {
          post blocks_url, params: { block: invalid_attributes }
        }.to change(Block, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post blocks_url, params: { block: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested block" do
        block = Block.create! valid_attributes
        patch block_url(block), params: { block: new_attributes }
        block.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the block" do
        block = Block.create! valid_attributes
        patch block_url(block), params: { block: new_attributes }
        block.reload
        expect(response).to redirect_to(block_url(block))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        block = Block.create! valid_attributes
        patch block_url(block), params: { block: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested block" do
      block = Block.create! valid_attributes
      expect {
        delete block_url(block)
      }.to change(Block, :count).by(-1)
    end

    it "redirects to the blocks list" do
      block = Block.create! valid_attributes
      delete block_url(block)
      expect(response).to redirect_to(blocks_url)
    end
  end
end
