 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/covers", type: :request do
  # Cover. As you add validations to Cover, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cover.create! valid_attributes
      get covers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cover = Cover.create! valid_attributes
      get cover_url(cover)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cover_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      cover = Cover.create! valid_attributes
      get edit_cover_url(cover)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cover" do
        expect {
          post covers_url, params: { cover: valid_attributes }
        }.to change(Cover, :count).by(1)
      end

      it "redirects to the created cover" do
        post covers_url, params: { cover: valid_attributes }
        expect(response).to redirect_to(cover_url(Cover.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cover" do
        expect {
          post covers_url, params: { cover: invalid_attributes }
        }.to change(Cover, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post covers_url, params: { cover: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cover" do
        cover = Cover.create! valid_attributes
        patch cover_url(cover), params: { cover: new_attributes }
        cover.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cover" do
        cover = Cover.create! valid_attributes
        patch cover_url(cover), params: { cover: new_attributes }
        cover.reload
        expect(response).to redirect_to(cover_url(cover))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cover = Cover.create! valid_attributes
        patch cover_url(cover), params: { cover: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cover" do
      cover = Cover.create! valid_attributes
      expect {
        delete cover_url(cover)
      }.to change(Cover, :count).by(-1)
    end

    it "redirects to the covers list" do
      cover = Cover.create! valid_attributes
      delete cover_url(cover)
      expect(response).to redirect_to(covers_url)
    end
  end
end
