require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/demobs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Demob. As you add validations to Demob, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Demob.create! valid_attributes
      get demobs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      demob = Demob.create! valid_attributes
      get demob_url(demob)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_demob_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      demob = Demob.create! valid_attributes
      get edit_demob_url(demob)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Demob" do
        expect {
          post demobs_url, params: { demob: valid_attributes }
        }.to change(Demob, :count).by(1)
      end

      it "redirects to the created demob" do
        post demobs_url, params: { demob: valid_attributes }
        expect(response).to redirect_to(demob_url(Demob.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Demob" do
        expect {
          post demobs_url, params: { demob: invalid_attributes }
        }.to change(Demob, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post demobs_url, params: { demob: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested demob" do
        demob = Demob.create! valid_attributes
        patch demob_url(demob), params: { demob: new_attributes }
        demob.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the demob" do
        demob = Demob.create! valid_attributes
        patch demob_url(demob), params: { demob: new_attributes }
        demob.reload
        expect(response).to redirect_to(demob_url(demob))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        demob = Demob.create! valid_attributes
        patch demob_url(demob), params: { demob: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested demob" do
      demob = Demob.create! valid_attributes
      expect {
        delete demob_url(demob)
      }.to change(Demob, :count).by(-1)
    end

    it "redirects to the demobs list" do
      demob = Demob.create! valid_attributes
      delete demob_url(demob)
      expect(response).to redirect_to(demobs_url)
    end
  end
end
