# This file contains configurations for both PostgreSQL and MySQL, uncomment
# the one you wish to use and keep the other commented out.

# -------------------------------- PostgreSQL ----------------------------------
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # The following username and password are used for both development and test
  # environments.
  username: 
  password: 

development:
  <<: *default
  database: action_plan_development

test:
  <<: *default
  database: action_plan_test

production:
  <<: *default
  # HEROKU
  # Heroku uses the DATABASE_URL environment variable to configure the DB
  # connection. You should *NOT* set adapter, database, username, password, host
  # or port in this file.
