require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FreqsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Freq. As you add validations to Freq, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FreqsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all freqs as @freqs" do
      freq = Freq.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:freqs)).to eq([freq])
    end
  end

  describe "GET #show" do
    it "assigns the requested freq as @freq" do
      freq = Freq.create! valid_attributes
      get :show, params: {id: freq.to_param}, session: valid_session
      expect(assigns(:freq)).to eq(freq)
    end
  end

  describe "GET #new" do
    it "assigns a new freq as @freq" do
      get :new, params: {}, session: valid_session
      expect(assigns(:freq)).to be_a_new(Freq)
    end
  end

  describe "GET #edit" do
    it "assigns the requested freq as @freq" do
      freq = Freq.create! valid_attributes
      get :edit, params: {id: freq.to_param}, session: valid_session
      expect(assigns(:freq)).to eq(freq)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Freq" do
        expect {
          post :create, params: {freq: valid_attributes}, session: valid_session
        }.to change(Freq, :count).by(1)
      end

      it "assigns a newly created freq as @freq" do
        post :create, params: {freq: valid_attributes}, session: valid_session
        expect(assigns(:freq)).to be_a(Freq)
        expect(assigns(:freq)).to be_persisted
      end

      it "redirects to the created freq" do
        post :create, params: {freq: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Freq.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved freq as @freq" do
        post :create, params: {freq: invalid_attributes}, session: valid_session
        expect(assigns(:freq)).to be_a_new(Freq)
      end

      it "re-renders the 'new' template" do
        post :create, params: {freq: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested freq" do
        freq = Freq.create! valid_attributes
        put :update, params: {id: freq.to_param, freq: new_attributes}, session: valid_session
        freq.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested freq as @freq" do
        freq = Freq.create! valid_attributes
        put :update, params: {id: freq.to_param, freq: valid_attributes}, session: valid_session
        expect(assigns(:freq)).to eq(freq)
      end

      it "redirects to the freq" do
        freq = Freq.create! valid_attributes
        put :update, params: {id: freq.to_param, freq: valid_attributes}, session: valid_session
        expect(response).to redirect_to(freq)
      end
    end

    context "with invalid params" do
      it "assigns the freq as @freq" do
        freq = Freq.create! valid_attributes
        put :update, params: {id: freq.to_param, freq: invalid_attributes}, session: valid_session
        expect(assigns(:freq)).to eq(freq)
      end

      it "re-renders the 'edit' template" do
        freq = Freq.create! valid_attributes
        put :update, params: {id: freq.to_param, freq: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested freq" do
      freq = Freq.create! valid_attributes
      expect {
        delete :destroy, params: {id: freq.to_param}, session: valid_session
      }.to change(Freq, :count).by(-1)
    end

    it "redirects to the freqs list" do
      freq = Freq.create! valid_attributes
      delete :destroy, params: {id: freq.to_param}, session: valid_session
      expect(response).to redirect_to(freqs_url)
    end
  end

end
